development:
  adapter: mysql
  database: penwood_development
  username: root
  password: 
  host: localhost
     

test:
  adapter: mysql
  database: penwood_test
  username: penwood_test
  password: penw00d
  host: localhost

production:
  adapter: mysql
  database: penwood_production
  username: penwood
  password: penw00d
  host: localhost
